### ISSUE TITLE
server status: [down]

### ISSUE THREAD

**Issue by jackpenny101** [AugustMiller/homebridge-minecraft-server#1]
Hello, my Bedrock (Nukkit) server running on a RPi is showing as down. The API status correctly says the server is running  & ocupied. 

I have another sever set up in Oracle cloud which is working fine (thanks!).

**Comment by AugustMiller** [comment]
Ah, interesting. Bedrock servers appear to use a different API URL than regular servers:

https://api.mcsrvstat.us/

I can add a toggle/selector in the accessory settings for the scheme!

**Comment by AugustMiller** [comment]
Just pushed a patch for this! You should be able to `git pull` wherever you checked out the plugin and open up its settings pane—or just add a new `type` key to the config file, directly, with a string value of `bedrock`.

![Screen Shot 2023-11-02 at 11 43 08](https://github.com/AugustMiller/homebridge-minecraft-server/assets/1895522/dd2a4272-f05e-4e11-99f8-908e9cf3e603)
